### ISSUE TITLE
Improving Error Reporting (ongoing)

### ISSUE THREAD

**Issue by zinkem5** [F5Networks/f5-appsvcs-templates#12]
This thread is meant to track confusing and useless error reporting in the FAST RPM.

Please report and feel free to discuss any and all displeasing error behavior in this thread, it will be monitored by the FAST development team.

**Comment by DumpySquare** [comment]
report proper error when supporting json template references is not found, like the types.json for the simple_udp_defaults.yml - it currently fails a JS promise.
```
Template set "goodFastTemplates" failed validation: Error: Failed to find the specified schema: types at c:\Users\bunoo\vscode-f5-fast\node_modules\@f5devcentral\f5-fast-core\lib\template.js:186:27 at Array.reduce (<anonymous>) at Template._handleParsed (c:\Users\bunoo\vscode-f5-fast\node_modules\@f5devcentral\f5-fast-core\lib\template.js:179:31) at Template._parametersSchemaFromTemplate (c:\Users\bunoo\vscode-f5-fast\node_modules\@f5devcentral\f5-fast-core\lib\template.js:395:39) at c:\Users\bunoo\vscode-f5-fast\node_modules\@f5devcentral\f5-fast-core\lib\template.js:519:22 at async Promise.all (index 1)
```

**Comment by mstokes-f5** [comment]
FAST versions 1.3.0, 1.4.0, 1.5.0 have been released since this issue was opened, and all have had significant improvements to error reporting. At this point specific issues should be filed for better tracking. As such, I am closing this report.

@DumpySquare I believe newer versions of f5-fast-core handle that situation better. If not, please feel free to file a new issue on f5-fast-core.
