### ISSUE TITLE
Redeploy template after failed attempt

### ISSUE THREAD

**Issue by gwolfis** [F5Networks/f5-appsvcs-templates#24]
In the GUI, when a template fails this is shown in the log for the reason mentioned. It would be great to have the option here to be able to get filled in template back and start solving the issue instead of refilling each time after a failure.

Used versions
FAST version: 1.3.0
TMOS version: 15.1.0.4

**Comment by zinkem5** [comment]
Hi @gwolfis , thanks for your feature request.

It turns out that this feature is being worked on right now. There will be a button in the deploy log to re-load the template with the previously filled form values. 

It will be available in the next release of FAST, which is currently planned for October 13th. This date could change, but shouldn't drift far.

Thanks,
Matt

**Comment by mstokes-f5** [comment]
This feature is available as of FAST 1.4.0. A new button has been added to the Deploy Logs tab to "Modify and Resubmit Application". This button is available for failed and for successful deploy actions.
