### ISSUE TITLE
Rapid sequential template deployments result in AS3 failures

### ISSUE THREAD

**Issue by F5Debbie** [F5Networks/f5-appsvcs-templates#4]
AS3 does not support queuing.  A template must finish deploying before another can be deployed.

**Comment by shyawnkarim** [comment]
Thanks for reporting this issue. AS3 now has [burst handling](https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/userguide/burst-handling.html), which enables queuing. We are now tracking this enhancement with internal ID MYSTIQUE-329 in order to update FAST to take advantage of this new feature.

**Comment by shyawnkarim** [comment]
Burst handling was added to AS3 in version 3.23 and later that fixes this issue. Instructions on how to enable this feature can be found on [F5 CloudDocs](https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/userguide/burst-handling.html).

**Comment by mjmenger** [comment]
Under a modest sustained load, using [this approach](https://github.com/f5devcentral/as3-bluegreen/tree/master/fast/test) which includes enabling bursthandling, inconsistent errors were seen.
- Failures to authenticate to the FAST endpoint, which previously and subsequently succeed
- Responses that appear successful to the REST client, but which have "undefined Configuration operation in progress on device undefined, please try again in 2 minutes." errors in the FAST Deploy Log.

**Comment by frslater** [comment]
As long as the BIG-IP is being configured solely through AS3, you should be able to improve performance by using "unchecked mode."  See documentation. https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/refguide/unchecked-mode.html

**Comment by grf5** [comment]
This is still occurring with burst enabled if multiple deployments are sent against the same tenant. Is there any recommendation for handling these scenarios? 

![image](https://user-images.githubusercontent.com/23108173/115662467-05138600-a30d-11eb-8b87-e1386b408a4f.png)

**Comment by grf5** [comment]
Is there a recommended way to query AS3 for status before sending a declaration to ensure it's "ready" and the request will be processed?

**Comment by shyawnkarim** [comment]
Closing. We updated our documentation to say burst handling is not supported in [Release 1.15.0](https://github.com/F5Networks/f5-appsvcs-templates/releases/tag/v1.15.0). 

As a workaround, you can try sending multiple deployments in a single API call instead of one API call per template deployment. 

If there is still a need for rapid sequential template deployments, please open up another GitHub issue.
