### ISSUE TITLE
FAST input fields have no default property in FAST schema but a default value is displayed on BIG-IP FAST form

### ISSUE THREAD

**Issue by selinaarokiaswamy-GSLAB** [F5Networks/f5-appsvcs-templates#81]
### Environment
 * FAST RPM Version: 1.13.0
 * BIG-IP Version: 15.1.2.1

### Summary
The following FAST input fields have no default property in FAST schema but a default value is displayed on BIG-IP FAST form. Please refer below images for reference.
FAST input fields:
1. Percentage - Blue Green Template
2. Blue Pool Name - Blue Green Template
3. Green Pool Name - Blue Green Template
4. Application Name - Microsoft ADFS Application Template
5. Application Name - Microsoft Exchange Template
6. Exchange Domain Name - Microsoft Exchange Template
7. Specify the name of an existing BIG-IP SSL certificate - Microsoft Exchange Template
8. Application Name - Microsoft Sharepoint Template

<img width="869" alt="bluegreen default" src="https://user-images.githubusercontent.com/88710971/139801712-d0d8c5f2-3f00-479c-9180-1f9612138bc2.png">

<img width="840" alt="issue 1 fast schema" src="https://user-images.githubusercontent.com/88710971/139802236-3c1fd2a5-71ba-4ae7-8575-29970bf3fd5c.png">

### Steps To Reproduce
1. Go to iApps->Application Services -> Applications Lx -> F5 Application Services Templates 
2. Select any one of the above templates
3. Compare the input field values with the FAST schema
4. To view FAST Schema, Go to bottom of the page and expand Debug view
5. Click on Schema Tab from Debug view

### Expected Behavior
The FAST schema for the above fields should have a default property same as BIG-IP FAST UI

### Actual Behavior
The BIG-IP FAST UI displays default value for FAST input fields that do not have a default property in FAST schema

**Comment by shyawnkarim** [comment]
Thanks for reporting this issue. We are now tracking it internally with ID MYSTIQUE-471.

**Comment by shyawnkarim** [comment]
Some of these are not supposed to be defaults in the schema, as they are pre-fill example display-defaults only. Some of them are valid defaults, not just examples, and we have moved them to the schema defaults:

1. Percentage - Blue Green Template
2. Blue Pool Name - Blue Green Template
3. Green Pool Name - Blue Green Template

These will remain as pre-fill/example form defaults because they are not expected to always be a logical default:

4. Application Name - Microsoft ADFS Application Template
5. Application Name - Microsoft Exchange Template
6. Exchange Domain Name - Microsoft Exchange Template
7. Specify the name of an existing BIG-IP SSL certificate - Microsoft Exchange Template
8. Application Name - Microsoft Sharepoint Template

**Comment by shyawnkarim** [comment]
Closing.

This issue was resolved with [Release 1.14.0](https://github.com/F5Networks/f5-appsvcs-templates/releases/tag/v1.14.0).
