### ISSUE TITLE
HTTP 1.1 in Exchange template

### ISSUE THREAD

**Issue by mnolanf5** [F5Networks/f5-appsvcs-templates#99]
### Environment
 * FAST RPM Version:
 * BIG-IP Version: 15.x

### Summary

Current version of Exchange FAST template uses HTTP 1.1 in the send string of the monitors. Exchange now defaults to http2 so these monitors dont work

"send": "GET /owa/healthcheck.htm HTTP/1.1\r\nHost: {{app_fqdn:f5:bigip_name}}\r\nConnection: Close\r\n\r\n",

### Steps To Reproduce
List the steps to reproduce the behavior:

### Actual Behavior
A clear and concise description of what actually happens.
Please include any applicable error output.

**Comment by shyawnkarim** [comment]
Thanks for reporting this. We are now tracking this issue internally with ID MYSTIQUE-598.

**Comment by shyawnkarim** [comment]
We have begun looking into this. Can you send a me a qkview so that we can take a look at your monitor logs? You'll need to enable logging on the pool member. My email address is s.karim@f5.com.

Additionally, do you have `Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\HTTP\ParametersEnableHttp2Tls `
set to 1?
